language: node_js
dist: trusty
node_js:
  - "7"
install:
  - npm install hexo-cli -g
  - npm install hexo-generator-json-content --g
  - npm install
script:
  - git submodule init
  - git submodule update
  - chmod +x deploy.sh
  - hexo clean
  - hexo g
  - ./deploy.sh > /dev/null
branches:
  only:
    - raw