language: node_js
dist: trusty
node_js:
  - "7"
install:
  - npm install hexo-cli -g
  - npm install hexo-generator-json-content --g
  - npm un hexo-renderer-marked --save
  - npm install hexo-renderer-markdown-it --save
  - cd node_modules/hexo-renderer-markdown-it/
  - npm install markdown-it-checkbox --save
  - cd ../../
  - npm install
script:
  - chmod +x deploy.sh
  - hexo clean
  - hexo g
  - ./deploy.sh > /dev/null
branches:
  only:
    - raw
