
# html lang
language: zh-Hans


#Nav menu
menu:
  # only dark or light
  nav: dark
  bg: dark
  slots:
    - 主页
    - 归档
    - 投喂
  paths:
    - /
    - /archives
    - /donate
  colors:
    - ED1C24
    - 29ABE2
    - FBB03B
  search:
    btn:
      theme: warning
      outline: true

content:
  textlight: false
  theme: border-warning
  text: left

#Index in index.html
index:
  textlight: false
  theme: bg-light
  #start,center,end
  paginator: start
  more:
    text: more>>
    theme: warning
    outline: true

#Biocard
biocard:
  avatar: /avatar.png
  title: NPofSi
  bio: 即使在无比无聊的人间之里也有温暖的柠香小屋，欢迎来到铃奈庵！
  textlight: false
  theme: border-warning
  itemlight: false
  itemth: bg-lightx
  settings:
    items: true
    links: true
  items:
    PlayDev: http://play.google.com/store/apps/dev?id=5856452462277796135
  links:
    Github: https://github.com/npofsi
    Twitter: https://twitter.com/npofsi
    Medium: https://medium.com/@npofsi
    Patreon: https://www.patreon.com/npofsi
    RSS: https://blog.npofsi.pro/atom.xml


#TagsCard
tagcard:
  textlight: false
  theme: border-dark
  itemlight: false
  itemth: border-warning
  header: 'light btn-outline-warning'

#RecentPostCard
rpcard:
  textlight: false
  theme: border-dark
  itemlight: false
  itemth: border-warning
  header: 'light btn-outline-warning'

# Miscelaneous
favicon: /favicon.ico

# Github and Gitment
github:
  username: npofsi
  email: npofsi@outlook.com
  gitment:
    enable: false
    owner: npofsi     #你的 GitHub ID
    repo: BlogComments       #存储评论的 repo
    oauth:
      client_id: 91f845c80e9c695b0f7d           #client ID
      client_secret: 4f3b7efb72bf090eb67be2da75c572cf5fd44581 #client Secret

friends:
  JimmyTian: http://www.twznow.com/
  Hiiragi: http://blog.hiirachan.moe/
  Lakphy: http://lakphy.github.io/
  慕晓社: http://www.swiss126.icoc.cc/


# stylesheets loaded in the <head>
stylesheets:
- /css/kope.css

# scripts loaded in the end of the body
scripts:
- /js/kope.js
